# -*- coding: utf-8 -*-
"""agrupamento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbLFmWmrf55PL0cfgjOKPWr5XuR8hXfQ
"""

import numpy as np
from sklearn.cluster import KMeans

mv_rating = np.array([
 [1, 0, 0, 1],
 [1, 1, 0, 0],
 [0, 1, 1, 0],
 [0, 0, 1, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 1]
])

#treinar modelo
#num de clusters(grupos)
nc = 2

#inicializando o modelo
kmeans = KMeans (n_clusters=nc,
                 random_state=0,n_init=10)

#treinando o modelo
kmeans.fit(mv_rating)

group_ind = kmeans.predict(mv_rating)

# i de iteracao no lugar de contador
print("usuario pertence ao grupo: ")
for i, cluster in enumerate(group_ind):
  print(f"usuario {i+1} pertence ao grupo {cluster+1}")



print("\n Filmes assistidos: ") #\n pula linha
for i in range(len(mv_rating)) :
  assistidos = np.where(mv_rating[i]== 1)[0] + 1
  print(f"usuario {i+1} assistiu aos filmes: {assistidos}")

def recomendar_filmes(movie, mv_rating, group_ind):
  movie = np.array(movie)


  #encontrar o grupo do usuario com base em seu vetor
  usuario_id = len(mv_rating)
  group_user = kmeans.predict([movie])[0]

  #encontrar todos os usuarios no mesmo grupo
  usuarios_mesmo_grupo = [i for i in range (len(group_ind))
  if group_ind[i] == group_user]


  #filmes assistidos pelo usuario no mesmo grupo
  mv_recomend = set()
  for usuario in usuarios_mesmo_grupo :
   mv_rating_user = np.where(mv_rating[usuario] == 1) [0]
   mv_recomend.update(mv_rating_user)


  #remover filmes que o usuario ja viu
  mv_recomend = mv_recomend - set(np.where(movie == 1)[0])

  #ajustar os indices dos filmes recomendados
  mv_recomend = [movie+1 for movie in mv_recomend]

  return sorted(mv_recomend)



#saida\exemplo da funcao mv_recomend
movie_watched_user = [0 ,0 ,0 ,1] #vetor de filmes
#assistidos (por exemplo, assistiu aos filmes 1 e 3)
movie_recomend = recomendar_filmes(movie_watched_user, mv_rating,
                                        group_ind)

print(f"\n Filmes recomendados: {movie_recomend}")